# Generated by Django 5.1.7 on 2025-04-09 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('turno', models.CharField(choices=[('D', 'Dia (12h)'), ('N', 'Noite (12h)'), ('I', 'Inteiro (24h)')], max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escala do Usuário',
                'verbose_name_plural': 'Escalas dos Usuários',
                'ordering': ['data'],
                'unique_together': {('usuario', 'data')},
            },
        ),
    ]
