# Generated by Django 5.1.7 on 2025-04-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_escalausuario_confirmado_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalausuario',
            options={'ordering': ['data', 'usuario'], 'verbose_name': 'Escala do Usuário', 'verbose_name_plural': 'Escalas dos Usuários'},
        ),
        migrations.AlterField(
            model_name='escalausuario',
            name='confirmado_admin',
            field=models.BooleanField(default=False, verbose_name='Confirmado/Escalado'),
        ),
        migrations.AlterField(
            model_name='escalausuario',
            name='turno',
            field=models.CharField(choices=[('D', 'Dia (12h)'), ('N', 'Noite (12h)'), ('I', 'Inteiro (24h)'), ('M', 'Manhã (8h~14h)'), ('T', 'Tarde (14h~20h)'), ('A', 'Madrugada (20h~2h)')], max_length=1),
        ),
    ]
