# Generated by Django 5.1.7 on 2025-04-15 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escala", "0003_alter_escalausuario_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="escalausuario",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="escalausuario",
            name="confirmado_admin",
            field=models.BooleanField(
                default=False, verbose_name="Confirmado pelo Admin"
            ),
        ),
        migrations.AlterField(
            model_name="escalausuario",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="escalausuario",
            name="data",
            field=models.DateField(verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="escalausuario",
            name="turno",
            field=models.CharField(
                choices=[
                    ("D", "Dia (12h)"),
                    ("N", "Noite (12h)"),
                    ("I", "Inteiro (24h)"),
                    ("M", "Manhã (6h)"),
                    ("T", "Tarde (6h)"),
                    ("A", "Madrugada (6h)"),
                ],
                max_length=1,
                verbose_name="Turno",
            ),
        ),
        migrations.AlterField(
            model_name="escalausuario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalas_usuario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
