# Generated by Django 5.1.7 on 2025-04-15 15:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escala", "0004_alter_escalausuario_atualizado_em_and_more"),  # CORRETO
    ]

    operations = [
        migrations.CreateModel(
            name="ValorTurno",
            fields=[
                (
                    "turno_codigo",
                    models.CharField(
                        choices=[
                            ("D", "Dia (12h)"),
                            ("N", "Noite (12h)"),
                            ("I", "Inteiro (24h)"),
                            ("M", "Manhã (6h)"),
                            ("T", "Tarde (6h)"),
                            ("A", "Madrugada (6h)"),
                        ],
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Código do Turno",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor base atual para este tipo de turno.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor Atual (R$)",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        help_text='Opcional: Ex: "Valor reajustado em 01/2026"',
                        max_length=100,
                        verbose_name="Descrição/Observação",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de Turno",
                "verbose_name_plural": "Valores dos Turnos",
                "ordering": ["turno_codigo"],
            },
        ),
    ]
