# Generated by Django 5.1.7 on 2025-04-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(help_text='Digite apenas os números do CPF.', max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
