# Generated by Django 5.1.7 on 2025-04-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
